---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
               - '*/perf'
              uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'
server:
  port: 8888